version: 2.1
orbs:
  ruby: circleci/ruby@1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.4-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run: bundle install
      - run:
          name: lint
          command: bundle exec rubocop
      - run:
          name: test
          command: bundle exec rake
